import Link from "next/link";
import { DATA_MODE, listRunSummaries } from "@/lib/data";
import { loadSnapshot, loadSnapshotRuns, readNewsJson } from "@/lib/news";
import NewsRefresh from "@/components/NewsRefresh";
export const dynamic = "force-dynamic";
const date = (value?: string) => value ? new Intl.DateTimeFormat("pt-BR", { dateStyle: "medium", timeStyle: "short", timeZone: "America/Sao_Paulo" }).format(new Date(value)) : "Sem registro";
export default async function DashboardPage() {
  const [snapshot, snapshots, runs, status] = await Promise.all([loadSnapshot(), loadSnapshotRuns(), listRunSummaries(30), readNewsJson<{ok: boolean; attempted_at: string; error: string | null}>("status.json")]);
  const repo = process.env.NEWS_GITHUB_REPO?.trim() || "pedro-schuetze/news-engine";
  const stale = !snapshot || Date.now() - Date.parse(snapshot.fetched_at) > 4 * 3600_000;
  return <main className="space-y-8"><header className="iris-page-heading"><div><p className="microlabel">Operação editorial</p><h1>Painel da redação.</h1><p>Coletas, gerações e o que precisa da sua atenção.</p></div><NewsRefresh snapshotId={snapshot?.id} /></header>
    <section className="iris-metrics">{[["Última coleta", date(snapshot?.fetched_at)], ["Pautas na capa", String(snapshot?.stats.stories ?? 0)], ["Rodadas no histórico", String(snapshots.length)], ["Frequência prevista", "A cada 3 horas"]].map(([label, value]) => <div key={label}><p className="microlabel">{label}</p><strong>{value}</strong></div>)}</section>
    <section className="iris-panel"><div className="iris-section-title"><h2>Coleta de notícias</h2><span className={status?.ok === false || stale ? "text-warn" : "text-ok"}>{status?.ok === false ? "Última tentativa falhou" : stale ? "Coleta atrasada" : "Atualizada"}</span></div><p className="text-sm leading-relaxed text-ink-2">O GitHub solicita uma coleta às 00:07, 03:07, 06:07, 09:07, 12:07, 15:07, 18:07 e 21:07, no horário de Brasília. O início pode atrasar. Cada rodada preserva uma capa no Histórico e atualiza Hoje, sem chamadas de IA.</p><p className="mt-4 text-sm text-ink-2">Última tentativa: {date(status?.attempted_at)}.</p>{status?.error && <p role="alert" className="mt-3 rounded-lg bg-danger-soft p-3 text-sm text-danger">{status.error}</p>}<a className="mt-4 inline-block text-sm text-brand-ink" target="_blank" rel="noreferrer" href={`https://github.com/${repo}/actions/workflows/frontpage-snapshots.yml`}>Abrir execuções e logs no GitHub ↗</a></section>
    <section><div className="iris-section-title"><h2>Gerações e pipeline diário</h2><span>Últimas {runs.length}</span></div><p className="mb-4 text-sm text-ink-2">O pipeline diário é uma coleta complementar. Ele não substitui a capa de Hoje. Posts existentes continuam disponíveis no editor.</p><div className="overflow-x-auto rounded-2xl border border-line bg-panel"><table className="tbl"><thead><tr><th>Quando</th><th>Origem</th><th>Matérias</th><th>Posts</th><th>Duração</th><th>Alertas</th><th /></tr></thead><tbody>{runs.map(run => <tr key={run.file}><td>{date(run.started_at)}</td><td>{run.mode === "news" ? "Pauta do Hoje" : run.mode === "manual" ? "Criação manual" : "Pipeline diário"}</td><td>{run.articles_collected}</td><td>{run.stories_selected}</td><td>{Math.round(run.duration_seconds)}s</td><td>{run.errors || "—"}</td><td><Link className="text-brand-ink" href={`/iris/editor?run=${encodeURIComponent(run.file)}`}>Abrir no editor ↗</Link></td></tr>)}</tbody></table></div></section><p className="text-xs text-ink-3">Dados: {DATA_MODE === "github" ? "GitHub" : "arquivos locais"}. Tema e navegação não alteram posts aprovados ou publicados.</p></main>;
}
