"use client";
import { useState } from "react";
export default function IrisStoryEditor({ snapshotId, storyId, title, section, outlets }: { snapshotId:string; storyId:string; title:string; section:string; outlets:{name:string;url:string}[] }) {
  const [busy,setBusy]=useState(false); const [phase,setPhase]=useState(""); const [error,setError]=useState("");
  async function generate(){ setBusy(true); setError(""); setPhase("Lendo as matérias originais e escrevendo o post…"); try { const r=await fetch("/api/news/drafts",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({snapshot_id:snapshotId,story_id:storyId})}); const b=await r.json(); if(!r.ok) throw new Error([b.error || "Não deu para gerar o post.", ...(b.problems ?? [])].join(" · ")); setPhase("Texto salvo. Gerando três imagens por slide…");
      let warning = "";
      try { const media = await fetch("/api/media/"+b.story_id+"?run="+encodeURIComponent(b.run_file)+"&mode=ai",{method:"POST"}); if (!media.ok) warning = "images"; } catch { warning = "images"; }
      location.href=`/iris/editor?run=${encodeURIComponent(b.run_file)}${warning ? "&notice=images" : ""}`; } catch(e){setError(e instanceof Error?e.message:"Não deu para gerar o post.");setBusy(false);} }
  return <div className="mx-auto max-w-3xl"><p className="microlabel">pauta selecionada · {section || "Geral"}</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-navy">Criar post</h1><div className="mt-6 rounded-xl border border-line bg-panel p-6"><h2 className="text-xl font-semibold text-ink">{title}</h2><p className="mt-2 text-sm text-ink-2">O Iris lê os artigos disponíveis e escreve o post no tom editorial padrão.</p><h3 className="mt-6 text-xs font-bold uppercase tracking-widest text-ink-3">Fontes do Google News</h3><ul className="mt-3 space-y-2">{outlets.map((o)=><li key={o.url} className="flex items-center gap-2 text-sm"><span className="h-2 w-2 rounded-full bg-amber-400"/><a className="text-ink hover:text-brand" href={o.url} target="_blank" rel="noreferrer">{o.name}</a><span className="text-xs text-ink-3">leitura será tentada na geração</span></li>)}</ul><button onClick={generate} disabled={busy} className="mt-7 rounded-lg bg-ink px-4 py-2.5 text-sm font-semibold text-white hover:bg-brand disabled:opacity-50">{busy?phase:"Gerar post"}</button>{error&&<p className="mt-3 text-sm text-danger">{error}</p>}</div></div>;
}
